version: '2'
volumes:
  mysqldb:
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  
  app:
    build: .
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    ports:
      - "9000:9000"
